# Generated by Django 3.2.9 on 2021-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('location', models.CharField(max_length=150)),
                ('image', models.ImageField(default='default.jpg', upload_to='pics/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
