# Generated by Django 3.2.9 on 2021-12-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlog',
            name='description',
            field=models.TextField(),
        ),
    ]
