# Generated by Django 3.2.9 on 2021-12-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0003_auto_20211218_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlog',
            name='slug',
        ),
    ]
